import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Switcher from "@/components/Switcher";

export default function Home() {
  const [localStorageAvailable, setLocalStorageAvailable] = useState(false);

  useEffect(() => {
    setLocalStorageAvailable(!!window.localStorage);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="fixed top-0 left-0 right-0 bg-white dark:bg-darkBlue-500 dark:text-white">
        <div className="flex justify-between items-center p-3 h-16">
          <h1>Welcome to Next.js!</h1>
          {localStorageAvailable && <Switcher />}
        </div>
      </header>
      <main className="flex justify-center bg-gray-100 dark:bg-darkBlue-600 h-screen">
        <div className="py-[calc(1.5rem+4rem)] px-4 w-full">
          <div className="flex flex-col text-left font-poppins">
            <h1 className="text-black dark:text-white text-3xl font-semibold">
              Meurillon Eliot
            </h1>
            <h2 className="text-black dark:text-white text-base font-normal">
              Développeur Full-Stack
            </h2>
          </div>
        </div>
      </main>
    </>
  );
}
